### ISSUE TITLE
add firmware on the SPIne error

### ISSUE THREAD

**Issue by crusoe2000** [bgkatz/SPIne#2]
I have a problem to put the firmware on the SPIne
with ST-Link utility (v4.5) already oddly to connect to the taget I must be in hotplug mode, and when I flash with SPIne.bin I have the message Read out protection is activated

16:16:12: ST-LINK SN: 066CFF383133524157151329
16:16:12: V2J30M19
16:16:12: Connected via SWD.
16:16:12: SWD Frequency = 4.0 MHz.
16:16:12: Connection mode: HotPlug.
16:16:12: Debug in Low Power mode enabled.
16:16:13: Device ID: 0x431
16:16:13: Device family: STM32F411xC / E
16:16:36: Read out protection is activated.
16:17:03: Could not disable Read Out Protection!
16:17:13: Core is held in reset
16:17:13: Error occured during erase operation!
16:17:19: Programmed memory Checksum: 0x00000000

I also made an attempt to erase memory ship I also have the message Read out protection is activated
and the problem is on the two ships of the SPIne,
 I ask you if you have ever had this problem, and you would have an idea to solve my problem
thank.

for info I had no problem putting the firmware on Cheetah Driver Integrated V4 & USBtoCAN and they even ship STM32F446RET6

**Comment by bgkatz** [comment]
I have never seen this.  Which version did you build?

**Comment by crusoe2000** [comment]
SPIne revision 9:56747e76c9c1 & mbed-dev revision 179:97f825502e2a

**Comment by crusoe2000** [comment]
is there a way to force a reset of the ship to remove the protection, I attach a screenshot STM32 link with option byte
![capture_STM32]
(https://user-images.githubusercontent.com/67592124/95688206-65936f00-0bd6-11eb-8250-0ff138fce540.jpg)
